### ISSUE TITLE
why it no work :( 🔢 

### ISSUE THREAD

**Issue by efectual** [imbuedhope/pydep_tool#2]
Traceback (most recent call last):
  File "/opt/homebrew/bin/pydep", line 8, in <module>
    sys.exit(pydep())
             ^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydep_tool/__init__.py", line 105, in update
    res_info = get_res_info_by_file(path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydep_tool/_scanner.py", line 132, in get_res_info_by_file
    "dist": get_dist(res),
            ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydep_tool/_scanner.py", line 103, in get_dist
    mods = [
           ^
TypeError: 'NoneType' object is not iterable

**Comment by efectual** [comment]
updated

**Comment by imbuedhope** [comment]
I think this happened because there was a dist pkg in the env without any files, which is kind of bizzare.

I think I fixed it just now with f760f17 but lmk if it pops up again
